name: deploy-tibero-fdw-ubuntu20.04 

on:
  workflow_call:
    secrets:
      git-access-token:
        description: 'Access token for Github'
        required: true


env: 
  DEPLOY_REPO: tmaxopensql/tibero-fdw-dist
  BUILD_OS: ubuntu20.04

jobs:
  deploy-tibero-fdw-ubuntu:
    runs-on: ubuntu-20.04
    
    steps:      
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Add PGDG repository
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      
    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-14 postgresql-contrib-14 postgresql-server-dev-14
    
    - name: Build tibero-fdw 
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/lib
        make USE_PGXS=1
      
        
    - name: Checkout deploy replository
      uses: actions/checkout@v2
      with:
        repository: ${{ env.DEPLOY_REPO }}
        ref: main
        token: ${{ secrets.git-access-token }}
        path: tibero-fdw-dist
    
    - name: Deploy to tibero-fdw-dist
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        
        cp tibero_fdw.so tibero-fdw-dist/${{ env.BUILD_OS }}/
        cp tibero_fdw.control tibero-fdw-dist/${{ env.BUILD_OS }}/
        cp *.sql tibero-fdw-dist/${{ env.BUILD_OS }}/
        cp Makefile tibero-fdw-dist/${{ env.BUILD_OS }}/
        cp setenv.sh tibero-fdw-dist/${{ env.BUILD_OS }}/
        cp -r sql/ tibero-fdw-dist/${{ env.BUILD_OS }}/
        cp -r expected/ tibero-fdw-dist/${{ env.BUILD_OS }}/
        cd lib/
        cp * ../tibero-fdw-dist/${{ env.BUILD_OS }}/lib/
        
        cd ../tibero-fdw-dist/${{ env.BUILD_OS }}/
        git add .
        if [[ -n $(git diff --cached --exit-code) ]]; then
          git commit -m "Deploy libraries"
          git push origin main
        else
          echo "No changes to commit"
        fi

        
    
        
